### ISSUE TITLE
Params gold_weight is always 0?

### ISSUE THREAD

**Issue by lxx909546478** [yixinL7/BRIO#19]
Hello, Thanks for the great code. 
I found that params **gold_weight** is always 0 when training. What is gold summary loss designed for? Could I regardless it during training?
<img width="907" alt="image" src="https://user-images.githubusercontent.com/48379537/189519998-981fc976-0a68-4cb6-bc25-caeabe3a83e2.png">

**Comment by yixinL7** [comment]
Hi, thank you for your interest in our work. 
If `gold_weight` is a positive number, it would require the model to assign more probability mass to the reference summary than any candidate summaries. However, it is not used in this work, as we use cross-entropy loss for the reference summary.
To reimplement the experiments in this work you may ignore this during training.

**Comment by lxx909546478** [comment]
> Hi, thank you for your interest in our work. If `gold_weight` is a positive number, it would require the model to assign more probability mass to the reference summary than any candidate summaries. However, it is not used in this work, as we use cross-entropy loss for the reference summary. To reimplement the experiments in this work you may ignore this during training.

Okay, thanks for your reply.
