### ISSUE TITLE
Why do lower case for BARTCNN?

### ISSUE THREAD

**Issue by Ricardokevins** [yixinL7/BRIO#3]
Hi thank you for sharing your awesome work.
However i notice that you do lower case before tokenize the CNNDM data while using BRIO-CNN (based on BART)

I check the vocab in origin BART and your BRIO vocab(download from transformer model lib)
They all contain upper cased tokens.

Thank you for your reply

**Comment by yixinL7** [comment]
Hi! Thank you for your interest in our work.
It was mostly because we wanted to have a fair comparison with our previous work (SimCLS). I just uploaded the checkpoint with cased data to this repo as well as the HF hub: `Yale-LILY/brio-cnndm-cased`.

**Comment by Ricardokevins** [comment]
> Hi! Thank you for your interest in our work. It was mostly because we wanted to have a fair comparison with our previous work (SimCLS). I just uploaded the checkpoint with cased data to this repo as well as the HF hub: `Yale-LILY/brio-cnndm-cased`.

Thank you for your reply!
