### ISSUE TITLE
questions about ROUGE score

### ISSUE THREAD

**Issue by jeewoo1025** [yixinL7/BRIO#5]
Hello!
Thank you for releasing the code as an open source. It's very helpful to study "abstractive summarization"

I have two questions as follows:
1) Does **model_ranking.bin** mean **BRIO-Ctr** of [paper](https://arxiv.org/abs/2203.16804)? Please check if it is correct
  * model_ranking.bin => BRIO-Ctr of paper 
  * model_generation.bin => BRIO-Mul of paper
 <br>

2) After downloading **model_generation.bin file of XSum dataset**, I found the ROUGE score on XSum was measured slightly lower than the paper. Could you tell me why this happened?

▶ ROUGE score on XSum (I made it)
![issue_1](https://user-images.githubusercontent.com/39071676/172598492-975feefb-e8b4-46d4-acf5-dee633da8037.PNG)

▶ code
```python
# evaluate the model as a generator on XSum
python main.py --cuda --gpuid 0 --config xsum -e --model_pt xsum_paper/model_generation.bin -g

# calculate ROUGE score 
python cal_rouge.py --ref ./xsum/diverse/test.target.tokenized --hyp ./result/xsum_paper/test.out.tokenized -l
```

![issue_2](https://user-images.githubusercontent.com/39071676/172598480-e8765328-dd59-4a57-84e3-7f33cc6bc793.PNG)

**Comment by yixinL7** [comment]
Hi!

> Does model_ranking.bin mean BRIO-Ctr of [paper](https://arxiv.org/abs/2203.16804)? Please check if it is correct

Yes!

> After downloading model_generation.bin file of XSum dataset, I found the ROUGE score on XSum was measured slightly lower than the paper. Could you tell me why this happened?

It's hard to say without detailed information. Sometimes even a single difference in the version of a python package can cause this difference. I'd say you are on the right path here because the difference in ROUGE scores is small enough. Did you try to use `cal_rouge.py` to evaluate the provided output [file](https://github.com/yixinL7/BRIO/blob/main/output/xsum.test.ours.out)? This may help you locate the difference.

Please let me know if you have more questions.

**Comment by jeewoo1025** [comment]
Hi! 

My environment is below:
* python 3.8.12

**Comment by jeewoo1025** [comment]
Hi!

My environment is as follows:
`python 3.8.12`
`transformers 4.19.3`
`pyrouge 0.1.3`
`tensorboard 2.9.1`
`sentencepiece 0.1.96`
`nltk 3.7`

> Did you try to use cal_rouge.py to evaluate the provided output [file](https://github.com/yixinL7/BRIO/blob/main/output/xsum.test.ours.out)? This may help you locate the difference.

I tried and the results are `ROUGE-1  48.80`, `ROUGE-2  25.52`, `ROUGE-L  40.25`.
![image](https://user-images.githubusercontent.com/39071676/173735529-25debdbc-4b5b-4a15-8bf2-f1b181db2ee7.png)
