### ISSUE TITLE
MIT lincense?

### ISSUE THREAD

**Issue by seungeunrho** [yixinL7/BRIO#6]
Hello, I'm trying to use your results and codes in our team's research (for comparison only), but I'm not sure about what's possible and what I can't.

Could you please specify which license is used for this project? e.g. MIT, Apache, ...

Thank you.

**Comment by yixinL7** [comment]
Hi! For our results you don't need to worry about the license issue :) But it might be a good idea to check for the licenses of the datasets we used in our paper. 

- CNN/DailyMail -> https://github.com/abisee/cnn-dailymail
- XSum -> https://github.com/EdinburghNLP/XSum
- NYT -> https://catalog.ldc.upenn.edu/LDC2008T19

**Comment by seungeunrho** [comment]
Thank you! I will close the issue.
